### ISSUE TITLE
Recoil issue

### ISSUE THREAD

**Issue by ElizabethYupyy** [CrystalVapor/Crystal-Recoil-System#2]
Hello! i am trying to set recoil from bp, but it's not working ;(

i see in instructions '3. 在合适的时候为玩家的后座力组件设置后座力模板  | Set the recoil template for the player's recoil component at the right time'

But i can't set recoil template, i just don't have node 'set recoil pattern'
how to fix that?... how to work with recoil from BP?... 
help please ;D

![125](https://github.com/user-attachments/assets/2d621c39-f11a-45b7-aedb-a19a76ea7057)

**Comment by CrystalVapor** [comment]
Hi! I've read your issue, and hope these information can help you.
Q1. There's a translate problem with the “后坐力模板”, actually it should be “Recoil Pattern” rather than "recoil template", this is my oversight, feel sorry about that, i will correct that in next commit!
Q2. This plugin's logic part is designed for c++ first(and was used mostly in c++), i guess i forgot to add 'BlueprintCallable' meta to 'SetRecoilPattern' method and this will be add to postion in next commit, i think now you can call it from blueprint!
@see commit#9f749270

**Comment by ElizabethYupyy** [comment]
thank u!
